### ISSUE TITLE
Missing dependency: Cheerio

### ISSUE THREAD

**Issue by mdp** [sjinks/inline-csp-hash#1]
This module seems to [rely on Cheerio](https://github.com/sjinks/inline-csp-hash/blob/master/index.js#L1), but it's listed only as a [development dependency](https://github.com/sjinks/inline-csp-hash/blob/master/package.json#L24).

**Comment by sjinks** [comment]
Yes, you are right

**Comment by sjinks** [comment]
Merged, thank you!
